### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by SCUTykLin** [fudan-zvg/gaussian-raytracing#3]
Hello:
     I run the code in a docker and meet an Segmentation fault.
    
![image](https://github.com/user-attachments/assets/5657abc6-9b46-4485-864e-438f5c1da9ff)
And I found that the error occured in 
```
        self.gaussian_tracer = GaussianTracer(transmittance_min=transmittance_min)
```
in GaussianModel.

gpu drivers：551.34, cuda version: 12.2

Do you have any ideas? Or provide a docker file? Thanks

**Comment by wzy-99** [comment]
Have you solved the problem?

I found it is because of `optix::initialize()`, but have no idea about what caused it.

**Comment by Yubel426** [comment]
I'm having the same problem, any solutions or suggestions?

**Comment by jinyanSanny** [comment]
@SCUTykLin  Hello, how did you solve the promble of "an Segmentation fault"?

**Comment by SCUTykLin** [comment]
> @SCUTykLin Hello, how did you solve the promble of "an Segmentation fault"?

Yes, at first I try to run the code on wsl(win). I try gpu drivers from 510 - 550, and all drivers will report the same error-(Segmentation fault).

So I switched to Linux and used driver 535, and it worked fine. The most likely cause of this issue is an incorrect driver version, optix should work with specific version.

**Comment by SCUTykLin** [comment]
> @SCUTykLin Hello, how did you solve the promble of "an Segmentation fault"?

Please note the corresponding drivers for different versions of OptiX. And I highly recommend u run the code on linux, because I try different gpu drivers(510-550) on win(wsl) and not work.

**Comment by jinyanSanny** [comment]
@SCUTykLin  
Thank you for your suggestions.I haver tried gpu drivers 535 cuda12.4/cuda12.1, gpu drivers 550 cuda 12.4/cuda11.8, I run the code on ubuntu 20.04, but I have met the same promble of  "an Segmentation fault". Do you have any suggestions? What about your version of cuda?And whether cuda affects the optix?

**Comment by jinyanSanny** [comment]
And whether cuda affects the optix?

**Comment by SCUTykLin** [comment]
drivers: 535.183.01
cuda: 12.1
I think the cuda version would not affect the optix running, but drivers version will:
![image](https://github.com/user-attachments/assets/1e0883c4-e9ad-428a-a2c9-e1f6ff01fbab)

**Comment by Yubel426** [comment]
@jinyanSanny You can try installing it:
`sudo apt install libnvidia-gl-535`

**Comment by tangjm24** [comment]
enviroment: linux /  ubuntu 22.04
cuda: 11.8
driver: 550.67

which version of optix should I choose. I could not change my gpu driver version for some reason.
